### ISSUE TITLE
After installing with docker on local environment, I got an ERR_INVALID_REDIRECT

### ISSUE THREAD

**Issue by aalmangour** [HospitalRun/hospitalrun-server#106]
Dear All,

I followed the steps in the guide of installing hospital run on a local server, after doing all the steps and navigating to xxx.xxx:8055 I got ERR_INVALID_REDIRECT.

I checked and found that port 8055 already has a service listening on. So I don't know where's the problem?

I'm using a virtual machine from Linode, OS Ubuntu 16.

Logs:
![image](https://user-images.githubusercontent.com/25371349/40892661-cd8c8e3c-67a2-11e8-8bc3-eeadc0d18a3a.png)

**Comment by MatthewDorner** [comment]
Mine (local server being accessed via IP) only works if I put "https://xxx.xxx.xxx.xxx" , without the 8055. If I fail to set up an SSL cert, the only way I got it to work is via localhost on the server itself.

**Comment by MatthewDorner** [comment]
to update on this, on the current setup, port 8055 is http. the web server is set to redirect http traffic to https.  however, your installation probably failed to set up https access, so it can't redirect.

if your server has a publicly-accessible domain name and you entered the domain name in docker-compose.yml, you may be failing to get https set up due to the issue #111 is intended to fix. if you want to test a solution, just change your docker-compose.yml's nginx container port mappings to match the one in #111 (80 instead of 8055), or let me know if you want any help.
