### ISSUE TITLE
hospitalrun-server_nginx_1 exited with code 1

### ISSUE THREAD

**Issue by Arjanguglani** [HospitalRun/hospitalrun-server#125]
I was trying to setup Hospital Run Server on Google Cloud and I ran into the following error :

nginx_1          | Installation succeeded.

nginx_1          | Requested name 35.202.208.254 is an IP address. The Let's Encrypt certificate authority will not issue certificates for a bare IP address.

nginx_1          | 2018/09/13 01:56:47 [emerg] 218#218: BIO_new_file("/etc/letsencrypt/live/35.202.208.254/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file
 or directory:fopen('/etc/letsencrypt/live/35.202.208.254/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx_1          | nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/35.202.208.254/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/
etc/letsencrypt/live/35.202.208.254/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

hospitalrun-server_nginx_1 exited with code 1

Any ideas on how to fix it?

**Comment by MatthewDorner** [comment]
It's because you can't use an IP address for the DOMAIN_NAME in docker-compose.yml. It needs to be a domain name on the internet like www.mydomain.com, so it can request an SSL cert for that domain from LetsEncrypt and validate it.

If you don't have your server on a public domain, you can change the SSL_TYPE from "auto" to "self" and use your own SSL cert files (may have to create yourself, you can find instructions for creating a self-signed ssl cert here: https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-nginx-in-ubuntu-16-04).

This part of the configuration is described in the documentation here:
https://github.com/HospitalRun/hospitalrun-server/blob/master/DEPLOYMENT_GUIDE.md
