### ISSUE TITLE
Write CI/CD Script to Deploy to Digitial Ocean

### ISSUE THREAD

**Issue by donaldwasserman** [HospitalRun/hospitalrun-server#127]
Currently, there are no CI/CD abilities to deploy the server app anywhere. We need some basic deployment setup, so when we merge into a given branch, the code is automatically deployed to the appropriate environment. 

### Key Results
- A deployment script, written in ES6+ that can run in travis with no hard-coded configuration options
- Deployments + post install work should be done automatically
- Our preferred hosting environment is Digital Ocean, but the script itself should be configurable

**Comment by hpierce1102** [comment]
I'm spending some time on this. Here's my thoughts so far:

There seems to be some pre-existing travis-ci deployment stuff going on that's updating the docker registry with the latest images in `conf/travis-deploy.sh`. **However**, I'm not seeing that script being executed in any of the builds I'm looking through. I'm probably just looking in the wrong place.

At a high level, I think deployment would follow this process:

1. Update docker registry with newest images (which may, or may not already exist)
2. Make digital ocean server pull those changes
3. Begin running those changes. 

Assuming `travis-deploy.sh` already achieves step 1, only steps 2 and 3 remain. Some primarily googling suggests that using docker-machine is the way to go. But since that would be primarily shell scripts, it doesn't leave any room to create an ES6+ deployment script 😕. 

I'm going to have to do more research on this - which could take some significant time. But I'm interested to see if I can make this work. I could certainly use help, if anyone else is interested in this problem too.

**Comment by donaldwasserman** [comment]
Hey @hpierce1102 One thing that's somewhat changed since I created this ticket is the existance of github actions. I think we'll be able to leverage some of that to do a lot of they heavy lifting (the hospital run org is currently on the waiting list for access.

**Comment by damianesteban** [comment]
How about running this on Digital Ocean Kubernetes? I could set that up for sure.

**Comment by damianesteban** [comment]
Oh, I see you are running on Azure. I could help with that as well.

**Comment by fox1t** [comment]
Hi @damianesteban this issue is not in scope anymore. We already have configurations for all major CI/CD platforms. Would you mind to check them on the frontend repo and coordinate with @tehKapa if you think there is something that could be improved? Are you already on our slack?
