### ISSUE TITLE
SSL Certification Issue

### ISSUE THREAD

**Issue by leogzl** [HospitalRun/hospitalrun-server#96]
The SSL server seems not working immediately.

1. The opening port is 8055 but certbot requires opening port 80
2. The command in the nginx/Dockerfile should be:
It should be /etc/nginx/conf.d/defaultssl.**conf**
```
RUN envsubst < /etc/nginx/conf.d/default.conf.tmpl > /etc/nginx/conf.d/default.conf \
        && envsubst < /etc/nginx/conf.d/defaultssl.conf.tmpl > /etc/nginx/conf.d/defaultssl.conf
```

So I tested like this:
1. Create the SSL 
```
docker run -it --rm -p 443:443 -p 80:80 --name certbot \
   -v "<hospitalrun-server_path>/data/nginx/letsencrypt:/etc/letsencrypt" \
   certbot/certbot certonly --standalone -d <server_name>
```
2. Run the `docker-compose up --build -d`

**Comment by leogzl** [comment]
Addional comment:
I commented out all the certbot syntax on `nginx/conf/entrypoint.sh`

**Comment by drakemedic** [comment]
@tangollama I have submitted a very minor PR to correct the nginx/Dockerfile. It's my first attempt at a PR, so hopefully I've done it properly!

**Comment by stukalin** [comment]
@drakemedic @leogzl I've merged the PR. If that fixes the problem let's close the issue then.

**Comment by drakemedic** [comment]
It doesn't stop the installation failing unfortunately. But it corrects the typo.

**Comment by leogzl** [comment]
I may suggest the certification is built separately using my method above, only if SSL is necessary.
Running it as the package on building seems not a good idea.

There are a lot of factor that makes the SSL creation failed, but it should not affect the build of the docker itself.

**Comment by drakemedic** [comment]
The edit doesn't seem to have happened - have I made an error?

**Comment by drakemedic** [comment]
Ok, no probs. I think it doesn't work though - the cert generation failed and I had to install it separately to get hospitalrun working.

**Comment by MatthewDorner** [comment]
When SSL cert creation fails, it appears that it is applying the "default.conf" instead of "defaultssl.conf". But this "default.conf" doesn't work right and I think this is where a lot of people are ending up when they install, SSL fails and they just get weird http errors (invalid redirect, etc) when they try to access the server.

I changed some of the settings in "default.conf" and got it to serve me the login page, but the application wouldn't go past login and would give a security warning in my browser console. Is this application intended to work over regular http?

Anyway I am going to first look at how to make it easier for people to use their own SSL cert.

**Comment by drakemedic** [comment]
Yes, the "typo" appears not to be a typo as the script takes care of it.
However, as you say, the script doesn't work properly and it is necessary
to run the cert manually.

Paul

**Comment by MatthewDorner** [comment]
yeah, you probably did the same thing I did to use your own SSL cert: https://github.com/HospitalRun/hospitalrun-server/compare/master...MatthewDorner:ssl-workaround

But that just bypasses the automatic LetsEncrypt entirely, so now I'm trying for something that lets people do either one, like maybe if you copy your own cert into the conf folder, it'll use those and otherwise it'll try to use LetsEncrypt.

**Comment by MatthewDorner** [comment]
https://github.com/HospitalRun/hospitalrun-server/compare/master...MatthewDorner:use-own-cert

experimenting with this. I made an extra argument in docker-compose.yml where you set "auto", "self" or "none" for your cert type. if you use "self" you also must replace the dummy cert files with your real ones. i'm not experienced with docker, nginx or ssl certs, so any feedback is appreciated.

**Comment by MatthewDorner** [comment]
ok, I think I know why the letsencrypt cert generation is failing. We don't open port 80, so we rely on the TLS-SNI-01 challenge which operates over port 443. But TLS-SNI-01 was disabled earlier this year due to a security bug and won't be re-enabled: https://community.letsencrypt.org/t/important-what-you-need-to-know-about-tls-sni-validation-issues/50811.

**Comment by drakemedic** [comment]
Aha. That'll explain it. I could see that was happening, but didn't know
why. We'll done.
